<?php

use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\AuditLogController;
use App\Http\Controllers\Api\CrudController;
use App\Http\Controllers\Api\DashboardController;
use App\Http\Controllers\Api\DebtController;
use App\Http\Controllers\Api\HouseholdController;
use App\Http\Controllers\Api\HouseholdExcelController;
use App\Http\Controllers\Api\InvoiceController;
use App\Http\Controllers\Api\InvoiceSettingController;
use App\Http\Controllers\Api\PaymentController;
use App\Http\Controllers\Api\UserController;
use App\Http\Controllers\Api\RouteExcelController;
use App\Http\Controllers\Api\ReportController;
use App\Http\Controllers\Api\InventoryController;
use App\Http\Controllers\Api\DocumentController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function () {
    Route::post('auth/login', [AuthController::class, 'login'])->middleware('throttle:10,1');
    Route::middleware('auth:sanctum')->group(function () {
        Route::get('auth/me', [AuthController::class, 'me']);
        Route::post('auth/profile', [AuthController::class, 'updateProfile']);
        Route::post('auth/logout', [AuthController::class, 'logout']);
        Route::get('dashboard', DashboardController::class)->middleware('permission:dashboard.view');
        Route::prefix('inventory')->middleware('permission:inventory.manage')->group(function () {
            Route::get('options', [InventoryController::class, 'options']);
            Route::get('categories', [InventoryController::class, 'categories']);
            Route::post('categories', [InventoryController::class, 'storeCategory']);
            Route::put('categories/{category}', [InventoryController::class, 'updateCategory']);
            Route::delete('categories/{category}', [InventoryController::class, 'destroyCategory']);
            Route::get('warehouses', [InventoryController::class, 'warehouses']);
            Route::post('warehouses', [InventoryController::class, 'storeWarehouse']);
            Route::put('warehouses/{warehouse}', [InventoryController::class, 'updateWarehouse']);
            Route::delete('warehouses/{warehouse}', [InventoryController::class, 'destroyWarehouse']);
            Route::get('materials', [InventoryController::class, 'materials']);
            Route::post('materials', [InventoryController::class, 'storeMaterial']);
            Route::post('materials/{material}', [InventoryController::class, 'updateMaterial']);
            Route::delete('materials/{material}', [InventoryController::class, 'destroyMaterial']);
            Route::get('transactions', [InventoryController::class, 'transactions']);
            Route::post('transactions', [InventoryController::class, 'storeTransaction']);
            Route::get('stocks', [InventoryController::class, 'stocks']);
            Route::get('report', [InventoryController::class, 'report']);
            Route::get('report/export', [InventoryController::class, 'export']);
        });
        Route::prefix('documents')->group(function () {
            Route::get('options', [DocumentController::class, 'options']);
            Route::get('categories', [DocumentController::class, 'categories']);
            Route::post('categories', [DocumentController::class, 'storeCategory']);
            Route::put('categories/{category}', [DocumentController::class, 'updateCategory']);
            Route::delete('categories/{category}', [DocumentController::class, 'destroyCategory']);
            Route::post('categories/{id}/restore', [DocumentController::class, 'restoreCategory']);
            Route::get('{id}/preview', [DocumentController::class, 'preview'])->whereNumber('id');
            Route::get('{id}/download', [DocumentController::class, 'download'])->whereNumber('id');
            Route::post('{id}/restore', [DocumentController::class, 'restore'])->whereNumber('id');
            Route::get('/', [DocumentController::class, 'index']);
            Route::post('/', [DocumentController::class, 'store']);
            Route::post('{document}', [DocumentController::class, 'update'])->whereNumber('document');
            Route::delete('{document}', [DocumentController::class, 'destroy'])->whereNumber('document');
        });
        Route::get('audit-logs', [AuditLogController::class, 'index'])->middleware('permission:settings.manage');
        Route::get('reports/revenue', [ReportController::class, 'revenue'])->middleware('permission:reports.view');
        Route::get('reports/revenue/excel', [ReportController::class, 'excel'])->middleware('permission:reports.view');
        Route::get('reports/revenue/pdf', [ReportController::class, 'pdf'])->middleware('permission:reports.view');
        Route::get('payments', [PaymentController::class, 'index'])->middleware('permission:payments.view');
        Route::get('debts', [DebtController::class, 'index'])->middleware('permission:payments.view');
        Route::get('debts-export', [DebtController::class, 'export'])->middleware('permission:payments.view');
        Route::get('payments/options', [PaymentController::class, 'options'])->middleware('permission:payments.create');
        Route::post('payments', [PaymentController::class, 'store'])->middleware('permission:payments.create');
        Route::post('invoices/publish', [InvoiceController::class, 'publish'])->middleware('permission:payments.create');
        Route::get('invoices', [InvoiceController::class, 'index'])->middleware('permission:payments.view');
        Route::get('invoices-export', [InvoiceController::class, 'export'])->middleware('permission:payments.view');
        Route::get('payments/{payment}/receipt', [InvoiceController::class, 'receipt'])->middleware('permission:payments.view');
        Route::get('payments/{payment}/invoice', [InvoiceController::class, 'invoice'])->middleware('permission:payments.view');
        Route::get('invoice-settings', [InvoiceSettingController::class, 'index']);
        Route::put('invoice-settings', [InvoiceSettingController::class, 'update']);
        Route::get('households/{household}/payment-suggestion', [PaymentController::class, 'suggestion'])->middleware('permission:payments.create');
        Route::get('users/options', [UserController::class, 'options']);
        Route::apiResource('users', UserController::class)->except('show');
        Route::get('households-import/template', [HouseholdExcelController::class, 'template']);
        Route::get('households-export', [HouseholdController::class, 'export']);
        Route::post('households-import', [HouseholdExcelController::class, 'import']);
        Route::get('households/options', [HouseholdController::class, 'options']);
        Route::get('households/{household}/payments', [HouseholdController::class, 'payments']);
        Route::post('households/{id}/restore', [HouseholdController::class, 'restore']);
        Route::apiResource('households', HouseholdController::class)->except('show');
        Route::get('routes-import/template', [RouteExcelController::class, 'template']);
        Route::post('routes-import', [RouteExcelController::class, 'import']);
        Route::post('{resource}/{id}/restore', [CrudController::class, 'restore'])->whereIn('resource', ['provinces', 'wards', 'neighborhoods', 'routes', 'employees', 'services']);
        Route::get('{resource}', [CrudController::class, 'index'])->whereIn('resource', ['provinces', 'wards', 'neighborhoods', 'routes', 'employees', 'services', 'household-services', 'settings']);
        Route::post('{resource}', [CrudController::class, 'store'])->whereIn('resource', ['provinces', 'wards', 'neighborhoods', 'routes', 'employees', 'services', 'household-services', 'settings']);
        Route::put('{resource}/{id}', [CrudController::class, 'update'])->whereIn('resource', ['provinces', 'wards', 'neighborhoods', 'routes', 'employees', 'services', 'household-services', 'settings']);
        Route::delete('{resource}/{id}', [CrudController::class, 'destroy'])->whereIn('resource', ['provinces', 'wards', 'neighborhoods', 'routes', 'employees', 'services', 'household-services', 'settings']);
    });
});
