<script setup lang="ts">
import type { RevenuePoint } from '@/types/dashboard'
defineProps<{ points: RevenuePoint[]; max: number; range: string; loading: boolean }>()
const emit = defineEmits<{ range: [value:'6'|'12'|'year'] }>()
const compact = (v:number) => new Intl.NumberFormat('vi-VN',{notation:'compact',maximumFractionDigits:1}).format(v)
const money = (v:number) => new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(v)
function changeRange(value: string) { emit('range', value as '6'|'12'|'year') }
</script>
<template><v-card class="pa-4 pa-md-5 h-100" border rounded="xl"><div class="d-flex justify-space-between align-center ga-3 mb-5"><div><div class="text-h6 font-weight-bold">Doanh thu theo tháng</div><div class="text-caption text-medium-emphasis">So sánh với cùng kỳ năm trước</div></div><v-btn-toggle :model-value="range" density="compact" color="primary" mandatory divided @update:model-value="changeRange"><v-btn value="6">6 tháng</v-btn><v-btn value="12">12 tháng</v-btn><v-btn value="year">Theo năm</v-btn></v-btn-toggle></div><v-skeleton-loader v-if="loading" type="image" height="280" /><div v-else-if="!points.some(p=>p.current || p.previous)" class="empty-state"><v-icon icon="mdi-chart-line" size="48" /><div>Chưa có doanh thu trong kỳ</div></div><div v-else class="revenue-chart"><div v-for="(point,index) in points" :key="point.month" class="revenue-chart__group"><div class="revenue-chart__bars"><div class="revenue-bar revenue-bar--previous" :style="{height:`${point.previous/max*100}%`}"><v-tooltip activator="parent">Năm trước: {{ money(point.previous) }}</v-tooltip></div><div class="revenue-bar revenue-bar--current" :style="{height:`${point.current/max*100}%`}"><v-tooltip activator="parent">{{ point.label }}: {{ money(point.current) }}</v-tooltip></div></div><span v-if="points.length <= 6 || index % 2 === 0" class="revenue-chart__label">{{ point.label.slice(0,2) }}</span></div></div><div class="d-flex justify-center ga-5 text-caption mt-3"><span><i class="chart-dot bg-primary" />Năm nay</span><span><i class="chart-dot bg-blue-grey-lighten-3" />Năm trước</span><span class="text-medium-emphasis">Cao nhất {{ compact(max) }}</span></div></v-card></template>
